version: "3"
services:
  database:
    image: mysql:8.0
    # build: ./mysql/
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: root
      LANG: C.UTF-8
    restart: always
    # ports:
    #   - "3308:3306"
    volumes:
      - ./mysql/database.sql:/docker-entrypoint-initdb.d/database.sql
      - ./mysql/data:/var/lib/mysql
      - ./mysql/mycustom.cnf:/etc/mysql/conf.d/custom.cnf

  app:
    build: ./java/
    image: time-tracker:0.1
    container_name: time-tracker
    ports:
      - "6699:6699"
    # volumes:
    #   - ./target/*.jar /app.jar
    depends_on:
      - database
    links:
      - "database:db"
    restart: always