timetracker:
  build: .
  # ports:
  #   - "5000:5000"
  # environment:
  #   ENV : DEV
  # volumes:
  #   - ./app:/app
  # links:
  #   - mysql
  #   - java
database:
  image: timetracker/mysql:0.1
  environment:
      MYSQL_ROOT_PASSWORD: root
# app:
#   image: java:17.0
