version: "3"
services:
  database:
    image: mysql:8.0
    # build: ./mysql/
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: root
      LANG: C.UTF-8
      TZ: Asia/Novosibirsk
    restart: always
    # ports:
    #   - "3308:3306"
    volumes:
      - ./mysql/database.sql:/docker-entrypoint-initdb.d/database.sql
      - ./mysql/data:/var/lib/mysql
      - ./mysql/mycustom.cnf:/etc/mysql/conf.d/custom.cnf

  app:
    build: ./java/
    image: time-tracker:0.1
    container_name: time-tracker
    environment:
      APP_PORT: 6969
      TZ: Asia/Novosibirsk
      # LOG_LEVEL: INFO
      LOG_CONFIG: "-Dlog4j2.configurationFile=/logger/log4j2.xml -Dfile.encoding=UTF-8"
    ports:
      - "6969:6969"
    volumes:
      - ./java/app/logger:/logger
    depends_on:
      - database
    links:
      - "database:db"
    restart: always